name: 'lacework-code-security'
description: "Scan code with Lacework's Code Security offering"
author: 'Lacework'
inputs:
  classpath:
    description: 'Specify the Java classpath for SAST analysis'
    required: false
    default: ''
  libpath:
    description: 'Specify the Java libpath for SAST analysis'
    required: false
    default: ''
  classes:
    description: 'Classes directory or JAR file to analyze (DEPRECATED)'
    required: false
    default: '.'
  sources:
    description: 'Sources directory to analyze'
    required: false
    default: '.'
  target:
    description: 'One of old or new to represent which is being analyzed'
    required: false
  debug:
    description: 'Set to true to enable debug logging'
    required: false
    default: false
  token:
    description: 'Set to a GitHub token for the repository with write permissions for PRs to enable PR comments'
    required: false
  footer:
    description: 'A block of Markdown that will be appended to any PR comments posted'
    required: false
  tools:
    description: 'Comma separated list of tools to run'
    required: false
    default: 'sca'
  eval-indirect-dependencies:
    description: 'Show vulnerabilities found in transitive dependencies'
    required: false
    default: false
outputs:
  old-completed:
    description: 'If running a target called old, whether the analysis for this was completed'
    value: ${{ steps.run-analysis.outputs.old-completed }}
  new-completed:
    description: 'If running a target called new, whether the analysis for this was completed'
    value: ${{ steps.run-analysis.outputs.new-completed }}
  push-completed:
    description: 'If running a target called push, whether the analysis for this was completed'
    value: ${{ steps.run-analysis.outputs.push-completed }}
  display-completed:
    description: 'If displaying results, whether this was completed'
    value: ${{ steps.run-analysis.outputs.display-completed }}
  comment-posted:
    description: 'If a comment was posted, a link to this comment'
    value: ${{ steps.run-analysis.outputs.comment-posted }}
runs:
  using: 'composite'
  steps:
    - id: init
      shell: bash
      env:
        LACEWORK_ACTION_REF: '${{ github.action_ref }}'
      run: |
        echo "LACEWORK_START_TIME=$(date --rfc-3339=seconds)" >> $GITHUB_ENV
        echo "LACEWORK_CONTEXT_ID=$(echo $RANDOM | md5sum | head -c 32)" >> $GITHUB_ENV
        echo "LACEWORK_ACTION_REF=$(echo $LACEWORK_ACTION_REF)" >> $GITHUB_ENV
        SCA_VERSION=0.0.53
        SAST_VERSION=0.0.47
        curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash
        echo "cache-key=$(date +'%Y-%m-%d')-$SCA_VERSION-$SAST_VERSION" >> $GITHUB_OUTPUT
        echo "sca-version=$SCA_VERSION" >> $GITHUB_OUTPUT
        echo "sast-version=$SAST_VERSION" >> $GITHUB_OUTPUT
    - id: cache
      uses: actions/cache/restore@v3
      with:
        path: ~/.config/lacework/components
        key: lacework-${{ steps.init.outputs.cache-key }}
    - if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "::group::Installing Lacework CLI components"
        lacework --noninteractive -a "${LW_ACCOUNT_NAME}" -k "${LW_API_KEY}" -s "${LW_API_SECRET}" component install sca --version "${{ steps.init.outputs.sca-version }}"
        lacework --noninteractive -a "${LW_ACCOUNT_NAME}" -k "${LW_API_KEY}" -s "${LW_API_SECRET}" component install sast --version "${{ steps.init.outputs.sast-version }}"
        echo "::endgroup::"
        echo "::group::Printing Lacework CLI information"
        lacework --noninteractive -a "${LW_ACCOUNT_NAME}" -k "${LW_API_KEY}" -s "${LW_API_SECRET}" version
        lacework --noninteractive -a "${LW_ACCOUNT_NAME}" -k "${LW_API_KEY}" -s "${LW_API_SECRET}" component list
        echo "::endgroup::"
    - if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ~/.config/lacework/components
        key: lacework-${{ steps.init.outputs.cache-key }}
    - shell: bash
      run: |
        cp -r "${{ github.action_path }}" ../lacework-code-security
        cd ../lacework-code-security
        HUSKY=0 npm install
        npm run compile
        pip install yq
        yq -yi 'del(.runs.steps) | del(.outputs) | .runs.using="node16" | .runs.main="dist/src/index.js" | .runs.post="dist/src/post.js"' action.yaml
    - id: run-analysis
      uses: './../lacework-code-security'
      with:
        classpath: '${{ inputs.classpath }}'
        classes: '${{ inputs.classes }}'
        sources: '${{ inputs.sources }}'
        target: '${{ inputs.target }}'
        debug: '${{ inputs.debug }}'
        token: '${{ inputs.token }}'
        footer: '${{ inputs.footer }}'
        tools: '${{ inputs.tools }}'
        eval-indirect-dependencies: '${{ inputs.eval-indirect-dependencies }}'
